// import './burger'
// import './sliders'
// import './fixedMenu'
//import './scroll'
//import './micromodal'
// import './sendAjax'
//import './animate'
// import './pop-ap-services'
// import './antispam'
import './yandexMaps'
import './swiper'
import './imask'
import './buttonsPress'

